### ISSUE TITLE
Wrong file path in tutorial step 4

### ISSUE THREAD

**Issue by 4ng3l0** [buildo/book#40]
## description
The file path for queries.js is wrong in [step 4](http://book.buildo.io/frontend/tutorial/step_4.html), under the paragraph "Creating your first Query".

The text says 
"Then define your first avenger Query in src/app/queries.js"

when it should be
"Then define your first avenger Query in src/app/queries/queries.js"

**Comment by gabro** [comment]
Thanks for reporting! If you feel like, go ahead and fix it :)
Once the PR is merged it the book will update automatically!
